### ISSUE TITLE
daml code changes require a `make clean`

### ISSUE THREAD

**Issue by lucianojoublanc-da** [digital-asset/ex-bond-issuance#171]
If making changes to `*.daml` source files, running `make build` followed by `make start; make automation ; make ui` results in the UI not finding the `Issuer` master rules contract, and so the `Issuer Actions` tab is blank (i.e. no button for "ISSUE BOND" or "COMMISSION AUCTION"). I can however see the issuer's balances tab fine.

The way around this is to do a `make clean` and repeat the above, but this is obviously very inconvenient as it causes a full rebuild of everything.

**Comment by richardkapolnai-da** [comment]
Well `make build` only builds the DAR, not the ui. For that, you need `make buildui ui`.
I think we should either

- adopt a more sophisticated `Makefile` (like https://github.com/digital-asset/ex-supply-chain/blob/ERA-847-ui/Makefile )
- be more explicit in the README and possibly simplify the invocation to use just one command (I suppose the Makefile above brings this too)

**Comment by chrisnorris-da** [comment]
The new makefile now addresses this issue.
